name: Release packaging

on:
  pull_request:
    branches:
      - develop # To test
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        # TODO: replace this once https://github.com/actions/setup-java/pull/637 gets merged.
        uses: gmitch215/setup-java@6d2c5e1f82f180ae79f799f0ed6e3e5efb4e664d
        with:
          java-version: '17'
          distribution: 'jetbrains'

      - name: Linux packages
        run: |
          ./gradlew application:packageReleaseTarGz
          ./gradlew application:packageReleaseDeb
          ./gradlew application:packageReleaseRpm

      - name: Upload .tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: NeoRegex
          path: application/build/distribution/*.tar.gz

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: NeoRegex
          path: application/build/compose/binaries/main-release/deb/*.deb

      - name: Upload .rpm
        uses: actions/upload-artifact@v4
        with:
          name: NeoRegex
          path: application/build/compose/binaries/main-release/rpm/*.rpm